server {
    listen 80;

    location / {
        proxy_pass http://frontend:80;
    }

    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /oauth/ {
            proxy_pass http://zitadel:8080;
            proxy_set_header Host localhost:8081; # Wymuszamy nagłówek, którego pragnie Zitadel!
    }
}